// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2f551305-a65b-4282-8292-019cd378a2e8";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onGasChange();
void onHumidChange();
void onFanChange();
void onLightChange();
void onTempChange();

float gas;
CloudRelativeHumidity humid;
bool fan;
bool light;
CloudTemperature temp;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(gas, READWRITE, ON_CHANGE, onGasChange);
  ArduinoCloud.addProperty(humid, READWRITE, ON_CHANGE, onHumidChange);
  ArduinoCloud.addProperty(fan, READWRITE, ON_CHANGE, onFanChange);
  ArduinoCloud.addProperty(light, READWRITE, ON_CHANGE, onLightChange);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
